# Use official Codespaces image as base
FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye


# [Optional] Install any additional system packages, e.g. build-essential
RUN apt-get update && apt-get install -y build-essential
